"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](primary)\
$os\
$username\
[ ](bg:secondary fg:primary)\
$directory\
[ ](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[ ](fg:tertiary bg:accent)\
$c\
$cpp\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[ ](fg:accent bg:container)\
$docker_context\
[ ](fg:container bg:surface)\
$time\
[  ](fg:surface)\
"""

palette = 'matugen'

[os]
style = "bg:primary fg:on-primary"
disabled = true # Disabled by default

[username]
show_always = true
style_user = "bg:primary fg:on-primary"
style_root = "bg:primary fg:on-primary"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:secondary fg:on-secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = "  "

[c]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[cpp]
symbol = "  "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[docker_context]
symbol = "  "
style = "bg:container"
format = '[[ $symbol $context ](fg:on-container bg:container)]($style)'

[elixir]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[elm]
symbol = "  "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[git_branch]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on-tertiary bg:tertiary)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind) ](fg:on-tertiary bg:tertiary)]($style)'

[golang]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[gradle]
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[haskell]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[java]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[julia]
symbol = "  "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[nodejs]
symbol = ""
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[rust]
symbol = ""
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[scala]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:surface"
format = '[[  ♥ $time ](fg:on-surface bg:surface)]($style)'

[palettes.matugen]

primary = '#b9c3ff'
on-primary = '#202c61'
primary-container = '#384379'
on-primary-container = '#dde1ff'

secondary = '#c3c5dd'
on-secondary = '#2c2f42'
secondary-container = '#424659'
on-secondary-container = '#dfe1f9'

tertiary = '#e5bad9'
on-tertiary = '#44263e'
tertiary-container = '#5c3c56'
on-tertiary-container = '#ffd7f3'

error = '#ffb4ab'
on-error = '#690005'
error-container = '#93000a'
on-error-container = '#ffdad6'

surface = '#121318'
on-surface = '#e3e1e9'
surface-variant = '#45464f'
on-surface-variant = '#c6c5d0'

container = '#1f1f25'
on-container = '#e3e1e9'
container-high = '#292a2f'
container-low = '#1b1b21'

accent = '#e5bad9'
on-accent = '#44263e'

success = '#b9c3ff'

outline = '#90909a'
outline-variant = '#45464f'
